// ── content/about.js ──
// About page (rendered as syntax-highlighted code)
//
// Each line is an array of tokens: [{ text, cls }, ...]
// Token classes: kw=keyword, fn=function, str=string, cm=comment,
//   ty=type, pp=purple, var=variable, dc=docstring, punc=punctuation

const about = {
  name: 'about_me.py',
  lang: 'Python',
  icon: '🧑‍💻',
  iconClass: 'icon-py',
  type: 'code',
  content: [
    [{ text: '"""', cls: 'dc' }],
    [{ text: 'about_me.py — A little about who I am.', cls: 'dc' }],
    [{ text: '"""', cls: 'dc' }],
    [],
    [],
    [{ text: 'class', cls: 'kw' }, { text: ' SoftwareEngineer', cls: 'ty' }, { text: ':' }],
    [{ text: '    """A software engineer building systems for research."""', cls: 'dc' }],
    [],
    [{ text: '    ', cls: '' }, { text: 'def', cls: 'kw' }, { text: ' __init__', cls: 'fn' }, { text: '(', cls: 'punc' }, { text: 'self', cls: 'var' }, { text: '):', cls: 'punc' }],
    [{ text: '        self.name = ', cls: '' }, { text: '"Joshua Patterson"', cls: 'str' }],
    [{ text: '        self.title = ', cls: '' }, { text: '"Software Engineer"', cls: 'str' }],
    [{ text: '        self.location = ', cls: '' }, { text: '"Pensacola, FL"', cls: 'str' }],
    [{ text: '        self.employer = ', cls: '' }, { text: '"Florida Institute for Human & Machine Cognition"', cls: 'str' }],
    [],
    [{ text: '        ', cls: '' }, { text: '# Education', cls: 'cm' }],
    [{ text: '        self.education = {' }],
    [{ text: '            ', cls: '' }, { text: '"MS"', cls: 'str' }, { text: ': ' }, { text: '"Cybersecurity — Software & System Security, UWF"', cls: 'str' }, { text: ',' }],
    [{ text: '            ', cls: '' }, { text: '"BS"', cls: 'str' }, { text: ': ' }, { text: '"Software Design & Development, Minor in CS, UWF"', cls: 'str' }],
    [{ text: '        }' }],
    [],
    [{ text: '        ', cls: '' }, { text: '# Certifications', cls: 'cm' }],
    [{ text: '        self.certs = [' }, { text: '"CompTIA Security+"', cls: 'str' }, { text: ', ' }, { text: '"CITI Export Compliance"', cls: 'str' }, { text: ']' }],
    [],
    [{ text: '        ', cls: '' }, { text: '# Core interests & passions', cls: 'cm' }],
    [{ text: '        self.interests = [' }],
    [{ text: '            ', cls: '' }, { text: '"API design & microservices"', cls: 'str' }, { text: ',' }],
    [{ text: '            ', cls: '' }, { text: '"Data pipelines & automation"', cls: 'str' }, { text: ',' }],
    [{ text: '            ', cls: '' }, { text: '"Real-time systems (WebSockets)"', cls: 'str' }, { text: ',' }],
    [{ text: '            ', cls: '' }, { text: '"Experiment workflow automation"', cls: 'str' }, { text: ',' }],
    [{ text: '            ', cls: '' }, { text: '"Mentoring & code review"', cls: 'str' }],
    [{ text: '        ]' }],
    [],
    [{ text: '    ', cls: '' }, { text: 'def', cls: 'kw' }, { text: ' philosophy', cls: 'fn' }, { text: '(', cls: 'punc' }, { text: 'self', cls: 'var' }, { text: ') -> ', cls: 'punc' }, { text: 'str', cls: 'ty' }, { text: ':', cls: 'punc' }],
    [{ text: '        ', cls: '' }, { text: 'return', cls: 'pp' }, { text: ' (' }],
    [{ text: '            ', cls: '' }, { text: '"Write clean code. Build reliable systems. "', cls: 'str' }],
    [{ text: '            ', cls: '' }, { text: '"Automate everything worth automating. "', cls: 'str' }],
    [{ text: '            ', cls: '' }, { text: '"Keep it simple until simple doesn\'t work."', cls: 'str' }],
    [{ text: '        )' }],
    [],
    [],
    [{ text: 'if', cls: 'kw' }, { text: ' __name__ == ' }, { text: '"__main__"', cls: 'str' }, { text: ':' }],
    [{ text: '    me = SoftwareEngineer()' }],
    [{ text: '    ', cls: '' }, { text: 'print', cls: 'fn' }, { text: '(me.philosophy())' }],
  ]
};
